### ISSUE TITLE
【RPGツクールMZ用】自分で素材を用意した際の設定

### ISSUE THREAD

**Issue by karasumatorimaru** [SpriteStudio/SS6PlayerForWeb#111]
初めまして
つい最近、こちらのプラグインを知り早速導入して、自分で用意した素材を使ってみようとしたのですがうまく行きません

アニメーションの表示で
プラグインコマンド ssfbロード(loadSsfb) で ssfb ファイルと画像ファイルの読み込みし、登録します。こちらのコマンドはダウンロード完了するまでウェイトします。

とありますが、実際に設定しようとするとアニメパック名(ssae)の指定が要求されます。
こちらは、どこに格納したらいいのでしょうか？
アニメーションのディレクトリもssfbフォルダ直下となっているので
pngと〇〇.ssfbを格納し下記のように設定

◆プラグインコマンド：ss6player-rpgmakermz, ssfbロード
：　　　　　　　　　：ssfb ID = 1
：　　　　　　　　　：ssfbファイルパス = ○○.ssfb
◆プラグインコマンド：ss6player-rpgmakermz, アニメーションピクチャの設定
：　　　　　　　　　：ssfb ID = 1
：　　　　　　　　　：アニメパック名 = ○○
：　　　　　　　　　：アニメ名 = 〇〇
：　　　　　　　　　：スケールX = 1.0
：　　　　　　　　　：スケールY = 1.0
：　　　　　　　　　：再生ループ回数 = 1

上記で実行すると「Cannot read property 'defaultDataLength' of null」のエラー文が表示されます。

サイドビューエネミーに関してもアニメパックの詳しい記載が見当たらすエラーが発生してしまいます。
分からない事ばかりですので、ご教授いただけたらと思います。
宜しくお願い致します。

**Comment by Naruto** [comment]
ssfb には sspj のアニメーションが全て含まれます。
sspj には、複数のアニメーションを設定できます。
どうSpriteStudioにてデータを準備するかは、SpriteStudioデータのサンプルをダウンロードしてお試しいただけないでしょうか。
こちら試していただけると、ssfbに 複数のアニメーションを含めて動作させる構成が分かりやすいかと思います。
お手数ですが、よろしくお願いします。

https://www.webtech.co.jp/help/ja/spritestudio/download/sample/#character_anime

**Comment by karasumatorimaru** [comment]
回答ありがとうございます。
早速試してみまして無事に設定することが出来ました！
