### ISSUE TITLE
再生アニメを途中で切り替えた場合の、配下のインスタンスパーツのアニメを継続させたい

### ISSUE THREAD

**Issue by A-Ota** [SpriteStudio/SS6PlayerForWeb#122]
#74 と関連するIssueかもしれませんが、

```
// 素体アニメーション
bodyPlayer.Setup('body', 'anime_1');
bodyPlayer.Play();
// 配下のインスタンスパーツのアニメーション設定
bodyPlayer.ChangeInstanceAnime('parts1', .....);
```
とした後に素体のアニメーションを差し替える
```
bodyPlayer.Setup('body', 'anime_2')
bodyPlayer.Play()
```
とした場合に、ChangeInstanceAnimeで設定したインスタンスパーツのアニメーションが
リセットされる(anime_2のタイムラインの初期値になる)という挙動になっております。

この挙動自体は仕様として正しい気はするのですが、インスタンスパーツのアニメーション
を親パーツのアニメーションが変更されても、連続性を持って継続させたく思っております。

このような要求を実現する方法がありましたら、ご教授いただけますでしょうか。

**Comment by wtsera** [comment]
OPTPiX ユーザーサポート 瀬良です。

アニメーションの変更を行った際は、動作状況のリセットを行います。
インスタンスパーツについても、アニメーション側で制御をしていますので、親のリセットに伴い再生状況もリセットされます。
インスタンスパーツのアニメーションを、アニメーションチェンジの影響を受けず維持する場合は、
インスタンスパーツで組み込んでいるアニメーションを別アニメーションとして再生してください。
お手数をおかけしますが、よろしくお願いいたします。

**Comment by A-Ota** [comment]
こちら回答ありがとうございます。
プレイヤーの仕様とのことで理解いたしました。
