### ISSUE TITLE
【RPGツクールMZ用】ピクチャを１，２回表示した後、一度消去した後再表示すると際に2重、3重に表示される

### ISSUE THREAD

**Issue by fuurinnn** [SpriteStudio/SS6PlayerForWeb#147]
お世話になります。
過去の質問にもあったのですが、何度かピクチャを表示して多重になった後ピクチャの消去をして
もう一度画像を表示すると多重になってしまうのですが、多重表示にならないようにするためにはどうしたらよいでしょうか
スクリプトは最新のものを使用しているのですが、同じような状態になってしまいました。

![fb210f66e26937fe9d313e13c3a7b136](https://user-images.githubusercontent.com/106066775/169782830-a30e3a5d-a119-4fd2-9ca1-6e8591e150b9.png)
![122bbd85c53efab9769d48e067f9cd52](https://user-images.githubusercontent.com/106066775/169783843-d8078e6d-d04a-4b7d-9d04-7ca159b070a3.png)

よろしくお願いします！

**Comment by Naruto** [comment]
報告ありがとうございます。問題再現できました。

ss6player-rpgmakermz のそもそもの問題として、一つの Picture ID で複数個のアニメーションを表示する現行の仕様が、 MZ の Picture ID の仕様と一致していない気がしています。

ですので、改善案として Picture ID 一つに対して 1 つの ss6player を表示する仕様に変更したものをリリースしました。

確認よろしくお願いします。

**Comment by fuurinnn** [comment]
お疲れ様です！
最新版を確認しました。
多重に表示されることなく、きちんとピクチャの消去で消すこともできました。

ご対応ありがとうございます！

**Comment by Naruto** [comment]
クローズします
