### ISSUE TITLE
インスタンスの設定で開始フレームを設定してのループがちらつく

### ISSUE THREAD

**Issue by A-Ota** [SpriteStudio/SS6PlayerForWeb#151]
お世話になっております。
インスタンスパーツのインスタンスの設定で開始フレームを設定してループさせた場合に、
開始フレームより前のフレームが一瞬見えるような形でちらつきます。
サンプルプロジェクトを添付いたします。
[test3.zip](https://github.com/SpriteStudio/SS6PlayerForWeb/files/8879308/test3.zip)
body/anime_1のearインスタンスパーツの再生を0～20フレームまで再生後は20～80フレームを繰り返す
ようなアニメーションを作成しています。(20フレーム目にインスタンスの設定を仕込んでいます。)

SpriteStudioのツール上では問題ないですが、プレイヤー上ではちらつきが発生します。
再現動画も添付いたしますので、ご確認お願いします。
https://user-images.githubusercontent.com/5799155/173078944-b48e9fd6-bd9d-4151-a23f-50018e4b40a1.mp4
https://user-images.githubusercontent.com/5799155/173078994-a3d2a441-dfe3-4cde-aafa-422eaeb3f2d4.mp4

再現はdevelopブランチのb87cb8dで行いました。

**Comment by Naruto** [comment]
#152 で修正してみました。
確認お願いできますでしょうか。

**Comment by A-Ota** [comment]
確認してみました。
20フレーム目のちらつきが無くなり、その後も何ループか正常にされることを確認しました。
しかし、しばらくループを繰り返すと切れ目がおかしくなってしまいます。(添付動画9秒あたり)
こちら今回の対応で発生したものかは不明ですが、ご確認お願いできますでしょうか。

https://user-images.githubusercontent.com/5799155/174479511-00e6dc81-1589-40e8-a2cb-71ed9e7a6968.mp4

**Comment by A-Ota** [comment]
こちら対応状況どうでしょうか？
そもそも「独立動作」で「無限ループ」のインスタンスを親アニメの途中のフレームに差し込んでいるので、
親アニメの尺の影響を受けるのは仕方がない気もしており、かなり修正が難しそうな予感がしております。
setFrameを使った別のやり方での解決がありそうでしたので、こちらは不対応でも大丈夫です。

**Comment by A-Ota** [comment]
はい、承知しました。
それではこちらはCloseいたします。
