### ISSUE TITLE
Knight.ssbp.ssfbにてあるパーツが表示されていない

### ISSUE THREAD

**Issue by SpriteStudio** [SpriteStudio/SS6PlayerForWeb#25]
こちらのサンプルデータのssfb

https://github.com/SpriteStudio/SS6PlayerForWeb/tree/develop/TestData/MeshBone

オリジナルデータと見比べていて、不定形な生物の頭にあるプリンがWebPlayerでは表示されていない。おそらくは、4.1で追加されたジョイントの先のメッシュやボーンの追加等がサンプルのssfbに含まれていない可能性がある。
再度コンバートを行ってみてOKであればSDKのAnimatorへの4.1実装がなされていると思うがそうでない場合はSDKを修正する必要がありそうだ。

**Comment by Naruto** [comment]
現行のアニメーションデータでプリンが表示されているのでクローズします。
