### ISSUE TITLE
Don't need call `PIXI.Container.call(this)`

### ISSUE THREAD

**Issue by finscn** [SpriteStudio/SS6PlayerForWeb#29]
https://github.com/SpriteStudio/SS6PlayerForWeb/blob/c4ede60f293e68af8ba3a8fe5b551612500d3398/packages/ss6player-pixi/src/SS6Player.ts#L82

because it's called  `super()`

the `super()` in js , it equals to `PIXI.Container.call(this)`

**Comment by Naruto** [comment]
I've fixed at #32 
thanks.
