### ISSUE TITLE
インスタンスパーツ利用時の不具合について

### ISSUE THREAD

**Issue by A-Ota** [SpriteStudio/SS6PlayerForWeb#31]
お世話になっております。

インスタンスパーツを含むアニメーション再生時に以下の2点の問題が発生するようなので、起票しました。

1. インスタンスパーツの親パーツがZ軸回転した時のインスタンスパーツの回転起点がSpriteStudioのビュワー上と異なる。
2. インスタンスパーツの独立動作のチェックを入れた際に、アニメーション再生時にエラーが発生する場合がある。

再現用のプロジェクトファイルを添付いたしました。
[test.zip](https://github.com/SpriteStudio/SS6PlayerForWeb/files/4569623/test.zip)

`mySS6Player.Setup("test", "anime_1")`にて1の再現が、
`mySS6Player.Setup("test", "anime_2")`にて2の再現ができます。

1については回転の起点が添付ファイルの用に、左のSpriteStudio上のプレビューに対し、右のブラウザ上の動作時は回転の軸が耳の付け根ではなくなってしまいます。
![スクリーンショット 2020-05-03 13 24 09のコピー](https://user-images.githubusercontent.com/5799155/80898739-e4d86900-8d41-11ea-9583-a794e80a8136.png)

2については`SS6Player.ts`の`GetFrameData`にて`curFrameData.states(i)`でnullが返ってきてしまうようで、
独立動作チェック時は`SetFrameAnimation`の
```javascript
// 独立動作の場合
if (independent === true) {
  const delta = this.updateInterval * 0.1;

  this.liveFrame[ii] += delta;
  time = Math.floor(this.liveFrame[ii]);
}
```
の箇所にてtimeがNaNで入ってしまうことが根本原因のようです。

お手数ですが、ご確認いただけますでしょうか。

**Comment by Naruto** [comment]
お世話になっております。

ご指摘いただいた問題を修正し  `develop` ブランチに反映しました。

"anime_1", "anime_2" どちらも想定通りの動作になっていると思いますので、確認よろしくお願いいたします 🙇

**Comment by A-Ota** [comment]
お世話になっております。
こちら対応ありがとうございました。

> 1.について回転起点が設定されること
> 2.についてエラーが出ないこと

を確認いたしました。

恐縮ですが、まだ挙動について問題がありまして

[test.zip](https://github.com/SpriteStudio/SS6PlayerForWeb/files/4607360/test.zip)

上記のzipに発生している事象のムービーを格納したのでご確認いただけますでしょうか。

`SpriteStudio上.mov`がツール上での動きで、`ブラウザ上.mov`がブラウザ上での
動きになります。

> 1. 回転起点は設定されたが、接着点がずれている。
> 2. 尺60フレームの顔に、尺30フレームの耳をインスターンスパーツとして乗せているが、耳のアニメーションがおかしい。(親の尺60フレームと解釈してのスピードで、30フレームのアニメーションを繰り返している？)

上記2点について、ご確認いただきたく思います。

**Comment by Naruto** [comment]
#32 にて再生終了時に不用意なクリア処理を入れてしまったため #34 にて修正いたしました。

1. と 2. につきまして、こちらの開発環境では再現することができませんでした。

macOS Catalina の safari, firefox, chrome,  Windows 10 の Edge, chrome 等々, Android, iOS などで一通り動作確認をしてみました再現はできませんでした。
また、sspj から ssfb を生成してみたのですが二度目に提供いただいた  `test.zip` に同封している ssfb と同じバイナリができている状態でした。

再生環境についてご教示いただけないでしょうか。

よろしくお願いいたします。

**Comment by A-Ota** [comment]
こちら、最新版のSS6PlayerForWebを改めてcloneし直して試したところ、  
1. 2. の現象は発生せず、完全にSpriteStudio上の挙動と同じものが再生されました。  
どうやらこちらの最新版の反映が不完全だったようで、大変お手数をおかけしました。

本件はcloseさせていただきます。対応ありがとうございました。
