### ISSUE TITLE
インスタンスパーツの回転起点について

### ISSUE THREAD

**Issue by A-Ota** [SpriteStudio/SS6PlayerForWeb#35]
お世話になっております。

#31 にてインスタンスパーツの回転に関して修正していただきましたが、
特定の条件下において類似の現象が発生してしまうようです。

具体的には、root階層直下に配置したパーツを回転させた場合、子のインスタンス
パーツの回転起点は問題ないのですが、
root階層 > 子パーツ1 > 子パーツ2 > インスタンスパーツ
のような構造の際に子パーツ2を回転させたときのインスタンスパーツの回転起点が
おかしくなるように思います。

[SS6PlayerForWeb_.zip](https://github.com/SpriteStudio/SS6PlayerForWeb/files/4642272/SS6PlayerForWeb_.zip)

プロジェクトを添付しましたので、ご確認いただけますでしょうか。
```
npm i
npm run bootstrap
npm run build
npm run view
```
にて動作する状態で固めてあります。
sspjプロジェクトは`TestData/test/body.sspj`となっております。

**Comment by Naruto** [comment]
お世話になっております。

#36 にて対応いたしました。
確認よろしくお願いいたします 🙇

**Comment by A-Ota** [comment]
お世話になっております。

最新版にて修正されていることを確認できました。
対応ありがとうございました！
