### ISSUE TITLE
ジョイントパーツの位置がずれてしまう

### ISSUE THREAD

**Issue by A-Ota** [SpriteStudio/SS6PlayerForWeb#38]
お世話になっております。
メッシュ・ボーン機能を使ったデータについて、プレイヤーで再生した際に
パーツの座標ずれの現象が発生してしまうので、起票しました。

[SS6PlayerForWeb.zip](https://github.com/SpriteStudio/SS6PlayerForWeb/files/4704793/SS6PlayerForWeb.zip)
```
npm i
npm run bootstrap
npm run build
npm run view
```
にて再現確認ができます。

> TestData/hair/101010045.sspj

こちらが該当プロジェクトで、joint_8とjoint_7がSpriteStudio上での再生と比べて
プレイヤーでの再生時にずれてしまいます。

> Sprite Studio 6.2.2.1186
> Ss6Converter (Build: Mar  4 2019 10:11:45)

にてデータを生成しております。

お手数ですが、調査をお願いできますでしょうか。

**Comment by wtsera** [comment]
お世話になっております。
ウェブテクノロジ ユーザーサポート 瀬良です。

こちら対応に時間がかかっており申し訳ございません。
現在も for Web側の調査、修正をすすめている状態です。

何らかの進展がありましたらご報告しますので、もうしばらくお待ちください。
よろしくお願いいたします。

**Comment by A-Ota** [comment]
回答ありがとうございます。
こちら急を要するものではありませんので、気長に進展を待ちたいと思います。

**Comment by Naruto** [comment]
お世話になっております。

#39 にて対応いたしました。
develop ブランチに反映済みです。
確認よろしくお願いいたします 🙇

**Comment by A-Ota** [comment]
お世話になっております。

修正されていることが確認できました。
対応ありがとうございました！
