### ISSUE TITLE
PIXI 5.0系へのアップデート要望

### ISSUE THREAD

**Issue by A-Ota** [SpriteStudio/SS6PlayerForWeb#40]
お世話になっております。
Issueというよりは要望/ご相談といった内容なのですが、PIXI 5.0系への対応は検討して
おりますでしょうか。

といいますのは、実は弊社でCocos2d-x版のPlayerを利用してアバターゲーム
を作成していたことがありまして、その際にパーツの優先度を絶対的な優先度
として取り扱うというカスタマイズをしておりました。

どのようなカスタマイズかと言いますと、次のような構成のアニメにおいて

- 親アニメ
  - 顔画像パーツ(優先度10)
  - 髪インスタンスパーツ(優先度11)
- 髪インスタンスパーツアニメ
  - 前髪画像パーツ(優先度15)
  - 後髪画像パーツ(優先度5)

本来は親アニメ内にてインスタンスパーツの優先度が11になっているため、
後髪パーツの優先度を5にしても、優先度10の顔画像パーツよりも
奥に表示することができないのを、できるようにするというものです。
(社内では「優先度のインスタンスパーツ越え」と呼んでおりました。)

こちらのカスタマイズを本家に入れて欲しいということではないのですが、
(Sprite Studioエディタ自体の仕様とも矛盾しますし)弊社で対応する際に、
PIXI 5系から用意された`sortableChildren`の機能を使えば楽に実現できそう
だと思った次第です。

https://github.com/pixijs/pixi.js/releases/tag/v5.0.0-rc
https://pixijs.download/dev/docs/PIXI.settings.html#.SORTABLE_CHILDREN

あるいは、現行の作りでここを変更すると楽にカスタマイズできそう、
とかがあればご教授いただきたいです。

現行の作りですと、addChild順の制御をする必要があると思うのですが、
それぞれのインスタンスパーツのSS6Playerが各々でTickerから更新されている
ので、なかなか難儀だなぁと思ってます💦

**Comment by Naruto** [comment]
お世話になっております。

Pixi.js v4 と v5 間で API の互換性がないため、 v5 へのバージョンアップへの二の足を踏んでいたのですが、今後は v5 が主流になることを考慮し、 ss6player-pixi v1.2.0 を pixi.js v4 対応の最終バージョンとし、以降は pixi.js v5 に対応することに致しました。

develop HEAD は pixi.js v5 対応となっておりますので確認よろしくお願いたします。

**Comment by Naruto** [comment]
#42

**Comment by A-Ota** [comment]
なんと・・！
それは大変にありがたいです。

develop HEADを追随しつつ、諸々の検証を行ってみます。

**Comment by Naruto** [comment]
アップグレードしたのでクローズといたします。
