### ISSUE TITLE
Playerの再生アニメを途中で変更できるようにして欲しい

### ISSUE THREAD

**Issue by A-Ota** [SpriteStudio/SS6PlayerForWeb#44]
お世話になっております。

要望があるのですが、`ss6PlayerPixi.SS6Player`にCocos2d-x版のプレイヤーでの`changeInstanceAnime`
https://github.com/SpriteStudio/SS6PlayerForCocos2d-x/blob/master/Cocos2d-x_v3/SSPlayer/SS6Player.h#L1365
に相当するメソッドを追加することは可能でしょうか。

現状、`SS6Player.Setup`によりssae名/anime名の指定ができますが2回以上呼び出すと、中途半端な
状態になってしまうようです。

※ 表示パーツは差し変わるが、キーフレームデータが変わらないようで、尺の長いアニメ＞尺の短いアニメ
の変更等を行うと、エラーが発生いたします。

**Comment by A-Ota** [comment]
確認いたしましたところ、問題なく機能しておりました。
対応ありがとうございました。

**Comment by Naruto** [comment]
確認ありがとうございます。
本チケットはクローズさせていただきます。
