### ISSUE TITLE
Player管理下のPIXI.Containerのnameプロパティについて

### ISSUE THREAD

**Issue by A-Ota** [SpriteStudio/SS6PlayerForWeb#45]
お世話になっております。

Player配下のchildren(PIXI.SimpleMesh, SS6Player, PIXI.Container等のPIXI.Containerサブクラス)に対して、
SpriteStudio上でのパーツ名を自動で割り当てる事は可能でしょうか。

現状、パーツ名を取得したいケースがあるのですが、SS6Player.GetFrameData等を経由する必要が
あるため、直接name属性から取得できたら便利なためです。

https://github.com/SpriteStudio/SS6PlayerForWeb/blob/develop/packages/ss6player-pixi/src/SS6Player.ts#L856
の箇所で
`mesh.name = part.name();`
を行うことで変更できましたが、問題なさそうであれば本家側で対応していただけると嬉しいです。

**Comment by Naruto** [comment]
お世話になっております。

develop HEAD にマージしました。
ご確認ください。

**Comment by A-Ota** [comment]
ありがとうございます。確認できました。
