### ISSUE TITLE
メッシュボーンアニメーションの描画不具合

### ISSUE THREAD

**Issue by A-Ota** [SpriteStudio/SS6PlayerForWeb#54]
お世話になっております。

メッシュボーンアニメーション付きのデータで、描画不具合が発生しております。
サンプルデータを添付したのでご確認いただけますでしょうか。

再現動画をzipファイル内に添付しております。
右下付近で顕著ですが、市松模様の継ぎ目がずれてしまっております。
[sample.zip](https://github.com/SpriteStudio/SS6PlayerForWeb/files/5200510/sample.zip)

**Comment by Naruto** [comment]
お世話になっております。

develop HEAD で確認しましたところ、同じ内容で描画されているのを確認しました。
再度 develop HEAD の方で確認お願いできますでしょうか。

よろしくお願いいたします。

**Comment by A-Ota** [comment]
こちらdevelop HEADを取り込んだところ正常に表示されました。
大変失礼いたしました。

**Comment by Naruto** [comment]
確認ありがとうございました！

クローズいたしますー
