### ISSUE TITLE
インスタンスパーツアニメーションの再生速度について

### ISSUE THREAD

**Issue by A-Ota** [SpriteStudio/SS6PlayerForWeb#69]
お世話になっております。
インスタンスパーツのアニメーションの再生速度が、設定したものよりも遅くなって
しまうという現象が発生しているので、調査をお願いできますでしょうか。

サンプルプロジェクトと再現動画を添付しました。

body.ssae/anime_1内のear_rは60フレームで1回転する一般パーツで、ear_lは60フレームで1回転するアニメ
を読み込んだインスタンスパーツとなっております。
インスタンスパーツは「独立動作」「無限ループ」を設定しております。
また、body.ssae/anime_1, ear.ssae/anime_1共に60fpsを設定しております。

[sample.zip](https://github.com/SpriteStudio/SS6PlayerForWeb/files/5401157/sample.zip)

**Comment by A-Ota** [comment]
SS6Player.ts
```typescript
          // 独立動作の場合
          if (independent === true) {
            const delta = this.updateInterval * (1.0 / this.curAnimation.fps());

            this.liveFrame[ii] += delta;
            time = Math.floor(this.liveFrame[ii]);
          }
```
こちらのdeltaの算出値が誤っているかもしれません。
親/子共に60fpsの場合、deltaを1にすると正常に動作致しました。

**Comment by Naruto** [comment]
助言ありがとうございます。
修正したので確認お願いできますでしょうか。

https://github.com/SpriteStudio/SS6PlayerForWeb/pull/76

**Comment by A-Ota** [comment]
動作させてみたところ、再生速度については修正されていることが確認できました。

ただ、親のアニメの尺が60フレーム、子のアニメの尺が80フレームとかの際に、
子のアニメが60フレーム目で1フレーム目に戻ってしまうような挙動となってしまいました。
(修正前は、子のアニメは遅くなるものの、独立で80フレームでのループを繰り替えしていました)

こちらご確認いただけますでしょうか。

**Comment by Naruto** [comment]
https://github.com/SpriteStudio/SS6PlayerForWeb/issues/69#issuecomment-728780370

こちら現在調査中です。
もうしばらくお待ちくださいませ。 🙇

**Comment by Naruto** [comment]
@A-Ota 
#80 にて修正いたしました。
確認よろしくお願いいたします。

**Comment by A-Ota** [comment]
お世話になっております。
こちら確かに修正が確認できました。

が、こちらの対応後に下記の現象が発生していますので、ご確認いただけますでしょうか。

アニメ > インスタンスパーツ > インスタンスパーツと、2階層先に設定したインスタンスパーツ
のアニメーションが再生されないという現象が発生しております。
上記の対応前は、再生速度の問題はあるものの、再生はされておりました。

再現用のプロジェクトを添付いたしました。
[再現確認用.zip](https://github.com/SpriteStudio/SS6PlayerForWeb/files/5743112/default.zip)

root.ssae > body.ssae > ear.ssaeとインスタンスパーツを設定しているのですが、
ear.ssae(左耳)が回転しなくなっております。

**Comment by Naruto** [comment]
#82 で修正しました。

インスタンスパーツ addChild 前に Pause を実行しているため、Update() で停止しているパーツとみなされ再生がされてませんでした。

Pause の実行をコメントアウトしました。
動作確認お願いできますでしょうか。

**Comment by A-Ota** [comment]
こちら修正が確認できました。
対応ありがとうございました。

**Comment by Naruto** [comment]
ありがとうございます

**Comment by Naruto** [comment]
こちらクローズさせていただきます
