### ISSUE TITLE
頂点変形時の左下頂点を起点に変形してしまう

### ISSUE THREAD

**Issue by A-Ota** [SpriteStudio/SS6PlayerForWeb#75]
お世話になっております。
頂点変形を使用した場合に、エディタとプレイヤーで異なる挙動となっているため、報告します。

再現時の動画とSpriteStudioプロジェクトを同梱しました。
[Issue.zip](https://github.com/SpriteStudio/SS6PlayerForWeb/files/5498351/Issue.zip)

どうやらプレイヤー上では、頂点変形後の左下座標が配置の起点となってしまうような
挙動に見えます。

**Comment by Naruto** [comment]
お世話になっております。
大変お待たせいたしました。 修正を施した PR を上げました。

確認お願いできますでしょうか。
https://github.com/SpriteStudio/SS6PlayerForWeb/pull/77

**Comment by A-Ota** [comment]
ありがとうございます。
こちら修正が確認できました。

対応ありがとうございました🙇

**Comment by Naruto** [comment]
確認ありがとうございます。
クローズさせていただきます。
