### ISSUE TITLE
【RPGツクールMZ用】シーン遷移後にアニメーションが非表示（？）になる？

### ISSUE THREAD

**Issue by sachinashi** [SpriteStudio/SS6PlayerForWeb#83]
SS6Player for RPG Maker MZを使用させていただいています。
おかげさまでsprite studioがツクールで使えるようになりました。
ありがとうございます。

表題の件に関しての質問です。

**＜現象＞**
MZのサンプルプロジェクトにて EV005 をゲーム中で起動すると、
MeshBone/Knight.ssbp.ssfb の Knight_bomb アニメパックが画面に表示されます。

その状態から、メニューシーンに遷移（またはバトルシーンに遷移）した後、
再びマップシーンに戻ると表示中だった Knight_bomb が消えています。

ツクールのデフォルト仕様では、ピクチャ扱いの画像は
（自発的に消去イベントを実行しない限り）マップに残り続けるもののため、
ss6player-rpgmakermz.js
内の仕様に依存した挙動かと思います。

**＜要望＞**
ss6player-rpgmakermz.js のピクチャ表示をツクールのデフォルトの仕様に近い挙動を実現することは出来ないでしょうか？
（画面の演出上、ピクチャを画面に残したままメニューシーンに遷移することも多いため）

コスト的な面も含めて、難しい場合には、その旨お伝えいただければ幸いです。
（自分でss6player-rpgmakermz.jsと格闘してみます）

ご一考いただければ幸いです。

**Comment by Naruto** [comment]
ご返答遅れてしまい申し訳ございません。

> ツクールのデフォルト仕様では、ピクチャ扱いの画像は（自発的に消去イベントを実行しない限り）マップに残り続けるもののため、
こちら、考慮が漏れてしまい申し訳ないです。
対応できるよう検討します。

**Comment by sachinashi** [comment]
Naruto様

お忙しい中、ご返信・ご検討頂きましてありがとうございます。
sachinashiです。

こちらでも packages\ss6player-rpgmakermz\src\ss6player-rpgmakermz.js を調べてみたのですが、
ツクールのピクチャと同様に扱うには「どこで sprite や bitmap を解放するべきか」を汎用的に決定するのが難しい、と痛感しました。

ピクチャは Scene_Map で表示されたあと、
・Scene_Battle に遷移しても
・Scene_Menu に遷移しても
・Scene_End に遷移しても
Scene_Map に戻ってくる可能性がある以上、
シーン遷移前後でピクチャの決め打ち解放をすることは難しそうです。

（Scene_End → Scene_Title の遷移では解放しても大丈夫っぽい）
（SVバトラー系は Scene_Battle が解放された時で問題なさそう）
（Scene_Base.prototype.terminateでの解放は間違い無く解放される安心感）

かといって、ずっと解放しないままであれば、
長時間稼働している内にメモリが圧迫されることも必定なので、
どこかのタイミングで解放することが求められるのも理解できます。

さしあたって思いつくのは、

１．「ピクチャの削除」イベントを経由して sprite studio 系のピクチャを削除する際に bitmap まで解放してしまう

手動ロードをすることが前提であれば、削除も自己責任で、という発想です。
昨今のスマートポインタの思想に反する手段ですが、一番容赦なく削除できるかと思います。
問題は複数の ss6player から参照されているビットマップの扱いでしょうか…？
（Aピクチャを削除したらBピクチャが参照していたビットマップがGCされてしまった、などが懸念）

２．マップ間移動時に、画面に表示されていない sprite studio 系のピクチャは解放してしまう

マップ内イベントで「ピクチャの削除」イベントにより削除された ss6player を保持しておき、
マップ間を移動した際に一気に当該の ss6player に紐づく bitmap を削除してしまう発想です。

削除のタイミングが決まっているので、bitmapの参照数を確認した上で解放することで、安全性は高められると思います。

こちらは手間はかかりますが…。


こちらでも何かしら実装をしてみようと思います。
もし良い知見がございましたらご教示いただけますと幸いです。
よろしくお願いします！

**Comment by Naruto** [comment]
@sachinashi

お待たせいたしました。 

#91  にて修正しました。
ご要望どおりの動作かご確認お願いできますでしょうか？

**Comment by sachinashi** [comment]
@Naruto 
ご対応いただきありがとうございました。

SS6PlayerForWeb-feature-mz\packages\ss6player-rpgmakermz\SampleProject\game.rmmzproject
からツクールMZ上での動作を確認させていただきました。

残念ながら、EV005で表示されたssfbアニメーションは
メニュー画面に遷移した後、マップに戻った際に非表示になってしまいました。
（visible が非表示になっただけなのか、ss6player が null になっているのかは分かりませんが）

こちらの確認不備かもしれませんので
「このプロジェクトを確認すればOK」というのがあれば
改めてご連絡もらえますと助かります。


（追伸：こちらのnpm周りの環境がグチャグチャになってしまったため、
プロジェクトのbuildがエラーを出しまくってしてしまい、
ソースの挙動詳細の確認は難しい状態になってしまいました）

**Comment by Naruto** [comment]
@sachinashi 
すみません。更新した ss6player-rpgmakermz を Sample Project への適応はしてませんでした。
そのため、 `SS6PlayerForWeb-feature-mz\packages\ss6player-rpgmakermz` で npm run deploy が必要でした。

先程同じブランチにて npm run deploy を実行したものを push しましたので、ご確認いただけると幸いです。

**Comment by sachinashi** [comment]
@Naruto
プロジェクト確認させて頂きました。

無事、マップ→ssfb表示→メニュー→マップで
ピクチャ表示された状態が維持されていました。

お忙しい中ご対応いただきありがとうございました。

**Comment by Naruto** [comment]
対応したものをリリースしました。
https://github.com/SpriteStudio/SS6PlayerForWeb/releases/tag/20210201

こちらのチケットはクローズします。
