### ISSUE TITLE
【RPGツクールMZ用】ピクチャを再表示した際に2重、3重に表示される

### ISSUE THREAD

**Issue by myOmochi** [SpriteStudio/SS6PlayerForWeb#95]
お世話になります！
表題の件につきましてご質問です。

●起こっていること
プラグインコマンドSS6Playerピクチャの設定で、再生ループ回数(-1)で表示し、不必要になった時点でピクチャ消去しています。
再度ピクチャを表示させると、ピクチャが2重に表示されます。表示させるたびにピクチャが増えていきます。
![image](https://user-images.githubusercontent.com/68860287/111056581-6f8e0680-84c3-11eb-9add-f7fb2ab9a2b2.png)

また、この状態でメニューに遷移するとエラーが発生し、ゲームが中断します。
`rmmz_managers.js:1968 Uncaught TypeError: Cannot read property 'getBuffer' of null
SceneManager.onError @ rmmz_managers.js:1968
rmmz_managers.js:1969 chrome-extension://njgcanhfjdabfmnlmpmdedalocpafnhl/js/libs/pixi.js 44222
SceneManager.onError @ rmmz_managers.js:1969
pixi.js:44222 Uncaught TypeError: Cannot read property 'getBuffer' of null
    at SimpleMesh.prototypeAccessors.vertices.set (pixi.js:44222)
    at SS6Player.SetFrameAnimation (ss6player-rpgmakermz.js:7517)
    at SS6Player.Update (ss6player-rpgmakermz.js:6675)
    at TickerListener.emit (pixi.js:9474)
    at Ticker.update (pixi.js:9928)
    at Ticker._tick (pixi.js:9679)`

●希望する状態
ピクチャ消去すると、一つしか表示されないようになると嬉しいです。
　
または、多重に表示されない方法があれば、教えていただけますと助かります。

よろしくお願いいたします。

**Comment by Naruto** [comment]
#105

**Comment by Naruto** [comment]
@myOmochi 
バグレポートありがとうございます。
問題を修正したものを 20210405 としてリリースしました。ご確認よろしくお願いいたします。
https://github.com/SpriteStudio/SS6PlayerForWeb/releases/tag/20210405

**Comment by myOmochi** [comment]
@Naruto 
修正版にて、問題が発生しないことを確認いたしました。
これで、立ち絵をSpriteStudioを使って表示したいとおもいます！

お忙しいところご対応いただき本当にありがとうございました！
